ajax/urls.py
from django.contrib import admin
from django.urls import path
from .views import users, free_days


urlpatterns = [
	path('users/', users, name='ajax-users'),
	path('days/', free_days, name='ajax-days')
]

carrent/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import Home_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', Home_view.as_view(), name='home'),

    path('', include('accounts.urls')),
    path('', include('userprofile.urls')),
    path('', include('sets.urls')),
    path('ajax/', include('ajax.urls')),
    path('', include('rents.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sets/urls.py
from django.urls import path, include
from .views import (
	UsersSettings, UserDetail, user_delete, CreateUser, UserEdit,
	CarsSettings, CarAdd, car_delete, CarDetail, CarEdit,
	Rents_list_admin, rent_delete,
)

urlpatterns = [
	path('userssettings/', UsersSettings.as_view(), name='users-settings'),
	path('user/<int:id>/', UserDetail.as_view(), name='user-detail'),
	path('userdelete/<int:id>/', user_delete, name='user-delete'),
	path('createuser/', CreateUser.as_view(), name='create-user'),
	path('useredit/<int:id>/', UserEdit.as_view(), name='user-edit'),

	path('carssettings/', CarsSettings.as_view(), name='cars-settings'),
	path('caradd/', CarAdd.as_view(), name='car-add'),
	path('cardelete/<int:id>/', car_delete, name='car-delete'),
	path('car/<int:id>/', CarDetail.as_view(), name='car-detaiil'),
	path('caredit/<int:id>/', CarEdit.as_view(), name='car-edit'),

	path('rentssettings/', Rents_list_admin.as_view(), name='rents-list-admin'),
	path('rentdelete/<int:id>/', rent_delete, name='rent-delete'),
]

sets/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput
from django.contrib.auth.models import User
import re
from django.core.exceptions import ValidationError
from .models import Headadmin, Employee, Client


class DateInput(forms.DateInput):
	input_type = 'date'

class MyAuthForm(AuthenticationForm):
	class Meta:
		model = User
		fields = ['username','password']
	def __init__(self, *args, **kwargs):
		super(MyAuthForm, self).__init__(*args, **kwargs)
		self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
		self.fields['username'].label = False
		self.fields['password'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'}) 
		self.fields['password'].label = False

class UserSignupForm(forms.Form):
	username				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'username',
										'class' : 'form-control form-control-left'}))

	password1				= forms.CharField(required = True,
								widget = forms.PasswordInput(
									attrs = {
										'placeholder' : 'password',
										'class' : 'form-control form-control-left'}))

	password2				= forms.CharField(required = True,
								widget = forms.PasswordInput(
									attrs = {
										'placeholder' : 'password',
										'class' : 'form-control form-control-left'}))

	first_name				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'first name',
										'class' : 'form-control form-control-left'}))

	last_name				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'last name',
										'class' : 'form-control form-control-left'}))

	email					= forms.EmailField(required = True,
								widget = forms.EmailInput(
									attrs = {
										'placeholder' : 'email',
										'class' : 'form-control form-control-left'}))
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

	def clean_username(self):
		username = self.cleaned_data['username'].lower()
		r = User.objects.filter(username=username)
		if r.count():
			raise  ValidationError("Username already exists")
		return username

	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		r = User.objects.filter(email=email)
		if r.count():
			raise  ValidationError("Email already exists")
		return email

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')

		if password1 and password2 and password1 != password2:
			raise ValidationError("Password don't match")

		return password2

class ClientSignupForm(forms.ModelForm):
	birth_date				= forms.DateField(required = True,  label="Birth_date",
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'birth date',
										'class' : 'form-control form-control-right',
										'onfocus': "(this.type='date')",
										'min': '01.01.1900',
										'max': '31.12.2020'}))

	pesel					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'pesel',
										'class' : 'form-control form-control-right',
										'maxlength': 11,
										'minlength': 11}))

	id_number				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'id number',
										'class' : 'form-control form-control-right',
										'maxlength': 7,
										'minlength': 7}))

	city					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'city',
										'class' : 'form-control form-control-right'}))

	street					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'street',
										'class' : 'form-control form-control-right'}))

	street_number			= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'street number',
										'class' : 'form-control form-control-right',
										'maxlength': 5}))

	postal_code				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'postal code',
										'class' : 'form-control form-control-right',
										'maxlength': 6,
										'minlength': 6}))

	class Meta:
		model = Client
		fields = ['birth_date', 'pesel', 'id_number', 'city', 'street', 'street_number', 'postal_code']

class EmployeeSignupForm(forms.ModelForm):
	birth_date				= forms.DateField(required = True,  label="Birth_date",
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'birth date',
										'class' : 'form-control form-control-right',
										'onfocus': "(this.type='date')",
										'min': '01.01.1900',
										'max': '31.12.2020'}))

	pesel					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'pesel',
										'class' : 'form-control form-control-right',
										'maxlength': 11,
										'minlength': 11}))

	id_number				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'id number',
										'class' : 'form-control form-control-right',
										'maxlength': 7,
										'minlength': 7}))

	city					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'city',
										'class' : 'form-control form-control-right'}))

	street					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'street',
										'class' : 'form-control form-control-right'}))

	street_number			= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'street number',
										'class' : 'form-control form-control-right',
										'maxlength': 5}))

	postal_code				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'postal code',
										'class' : 'form-control form-control-right',
										'maxlength': 6,
										'minlength': 6}))

	class Meta:
		model = Employee
		fields = ['birth_date', 'pesel', 'id_number', 'city', 'street', 'street_number', 'postal_code']

class HeadadminSignupForm(forms.ModelForm):
	birth_date				= forms.DateField(required = True,  label="Birth_date",
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'birth date',
										'class' : 'form-control form-control-right',
										'onfocus': "(this.type='date')",
										'min': '01.01.1900',
										'max': '31.12.2020'}))

	pesel					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'pesel',
										'class' : 'form-control form-control-right',
										'maxlength': 11,
										'minlength': 11}))

	id_number				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'id number',
										'class' : 'form-control form-control-right',
										'maxlength': 7,
										'minlength': 7}))

	city					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'city',
										'class' : 'form-control form-control-right'}))

	street					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'street',
										'class' : 'form-control form-control-right'}))

	street_number			= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'street number',
										'class' : 'form-control form-control-right',
										'maxlength': 5}))

	postal_code				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'postal code',
										'class' : 'form-control form-control-right',
										'maxlength': 6,
										'minlength': 6}))

	class Meta:
		model = Headadmin
		fields = ['birth_date', 'pesel', 'id_number', 'city', 'street', 'street_number', 'postal_code']

sets/templates/car_add.html
{% extends 'settingsBase.html' %}
{% load static %}

{% block css %}
		<link rel="stylesheet" href="{% static 'css/form.css' %}">

		<style>
			.banner{
				text-align: center;
				float: left;
				width: 100%;
			}
			.left{
				float: left;
				width: 50%;
			}
			.right{
				float: left;
				width: 50%;
			}
			.submitdiv{
				clear: both;
				float: left;
				width: 100%;
			}
			input, .custom-file, .checkdiv{
				margin-top: 0.7em;
			}
			.checkdiv{
				height: 38px;
				text-align: center;
			}
			.btn{
				margin-top: 2em;
			}
			.file-input{
				height: 38px;
			}
		</style>
{% endblock css %}

{% block content %}		<form method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="banner">
							<h1>Add car</h1>
						</div>
						<div class="left">
							{{ form.brand }}
							{{ form.model }}
							{{ form.generation }}
							{{ form.year_of_production }}
							{{ form.fuel_type }}
							{{ form.engine }}
							{{ form.hourse_power }}
							{{ form.body_type }}
						</div>
						<div class="right">
							{{ form.seats }}
							{{ form.doors }}
							{{ form.acceleration }}
							{{ form.max_speed }}
							{{ form.price }}
  							{{ form.image }}
							{{ form.other_info }}
							<div class="checkdiv">
								{{ form.to_rent }}{{ form.to_rent.label }}
							</div>
						</div>
						<div class="submitdiv">
							<button class="btn btn-lg btn-primary btn-block" type="submit" id="subbut">Add</button>
						</form>
						</div>
{% endblock content %}

sets/templates/car_detail.html
{% extends 'base.html' %}

{% block css %}
		<style type="text/css">
			.kkk{
				width: 100%;
				height: 100%;
			}
			.about{
				float: left;
				width: 25%;
			}
			.info{
				float: left;
				width: 75%;
			}
			.about, .info {
				margin-top: 2%;
			}
			.image{
				float: left;
				width: 40%;
				height: 100%;
			}
			.right{
				float: left;
				height: 100%;
				width: 60%;
			}
			.banner{
				float: left;
				width: 100%;
				height: 10%;
				text-align: center;
			}
			img{
				width: 100%;
				height: auto;
				padding: 10%;
			}
		</style>
{% endblock css %}

{% block content %}
						<div class="kkk">
							<div class="image">
								<img src="{{ car.image.url }}" alt="car">
							</div>
							<div class="right">
								<div class="banner">
									<h1>{{ car.brand }} {{ car.model }} {{ car.generation }}&nbsp&nbsp&nbsp&nbsp&nbsp <a href="/caredit/{{ car.id }}/"><span style="float: right; margin-right: 3%;">Edit this car</span></a></h1>
								</div>
								<div class="about">
									<p>Year of production:</p>
									<p>Body type:</p>
									<p>Seats:</p>
									<p>Doors:</p>
									<p>Engine:</p>
									<p>Hourse power:</p>
									<p>Fuel type:</p>
									<p>Acceleration:</p>
									<p>Max speed:</p>
									<p>Price:</p>
									<p>To rent:</p>
									<p>Other info:</p>
								</div>
								<div class="info">
									<p>{{ car.year_of_production }}</p>
									<p>{{ car.body_type }}</p>
									<p>{{ car.seats }}</p>
									<p>{{ car.doors }}</p>
									<p>{{ car.engine }}</p>
									<p>{{ car.hourse_power }}</p>
									<p>{{ car.fuel_type }}</p>
									<p>{{ car.acceleration }}</p>
									<p>{{ car.max_speed }}</p>
									<p>{{ car.price }}</p>
									<p>{{ car.to_rent }}</p>
									<p>{{ car.other_info }}</p>
								</div>
							</div>
						</div>
{% endblock content %}

sets/templates/car_edit.html
{% extends 'settingsBase.html' %}
{% load static %}

{% block css %}
		<link rel="stylesheet" href="{% static 'css/form.css' %}">

		<style>
			.banner{
				text-align: center;
				float: left;
				width: 100%;
			}
			.left{
				float: left;
				width: 50%;
			}
			.right{
				float: left;
				width: 50%;
			}
			.submitdiv{
				clear: both;
				float: left;
				width: 100%;
			}
			input, .custom-file, .checkdiv{
				margin-top: 0.7em;
			}
			.checkdiv{
				height: 38px;
				text-align: center;
			}
			.btn{
				margin-top: 2em;
			}
		</style>
{% endblock css %}

{% block content %}		<form method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="banner">
							<h1>Edit car</h1>
						</div>
						<div class="left">
							{{ form.brand }}
							{{ form.model }}
							{{ form.generation }}
							{{ form.year_of_production }}
							{{ form.fuel_type }}
							{{ form.engine }}
							{{ form.hourse_power }}
							{{ form.body_type }}
						</div>
						<div class="right">
							{{ form.seats }}
							{{ form.doors }}
							{{ form.acceleration }}
							{{ form.max_speed }}
							{{ form.price }}
							{{ form.image }}
							{{ form.other_info }}
							<div class="checkdiv">
								{{ form.to_rent }}{{ form.to_rent.label }}
							</div>
						</div>
						<div class="submitdiv">
							<button class="btn btn-lg btn-primary btn-block" type="submit" id="subbut">Edit</button>
						</form>
						</div>
{% endblock content %}

sets/templates/cars_settings.html
{% extends 'settingsBase.html' %}

{% block css %}
		<style type="text/css">
			.all {
				width: 100%;
				height: 100%;
				padding-bottom: 100px;
			}
			.banner{
				float: left;
				width: 100%;
				text-align: center;
			}
			.rest{
				float: left;
				width: 100%;
			}
			table{
				border: 1px solid black;
				width: 100%;
				text-align: center;
			}
			th{
				background-color: white;
				border: 1px solid black;
			}
			td{
				border: 1px solid black;
			}
			tr:nth-child(odd) {
				background-color: rgba(255, 255, 255, 0.5);
			}
			.btn{
				background-color: white;
				padding: 15px;
			}
		</style>
{% endblock css %}

{% block content %}
						<div class="all">
							<div class="banner">
								<h1 style="display: inline-block;">Manage cars</h1>
								<a href="{% url 'car-add' %}"><button class="btn" style="display: inline-block; float: right;">Add Car</button></a>
							</div>
							<div class="rest">
								<table id="cars_table">
									<tr>
										<th>Lp.</th>
										<th>Brand</th>
										<th>Model</th>
										<th>Year</th>
										<th>Engine</th>
										<th>Fuel</th>
										<th>To rent</th>
										<th>Detail</th>
										<th>Delete</th>
									</tr>
									{% for car in cars %}
									<tr>
										<td>{{ forloop.counter }}</td>
										<td>{{ car.brand }}</td>
										<td>{{ car.model }}</td>
										<td>{{ car.year_of_production }}</td>
										<td>{{ car.engine }}</td>
										<td>{{ car.fuel_type }}</td>
										<td>{{ car.to_rent }}</td>
										<td><a href="/car/{{ car.id }}"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/><path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/></svg></a></td>
										<td><a href="/cardelete/{{ car.id }}"><svg width='1em' height='1em' viewBox='0 0 16 16' class='bi bi-trash' fill='currentColor'><path d='M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z'/><path fill-rule='evenodd' d='M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z'/></svg></a></td>
									</tr>
									{% endfor %}
								</table>

							</div>
						</div><br><br><br><br><br><br>
{% endblock content %}

sets/templates/create_user.html
{% extends 'settingsBase.html' %}

{% block css %}
		<style type="text/css">
			.all {
				width: 100%;
				height: 100%;
				padding-bottom: 100px;
			}
			.banner{
				float: left;
				width: 100%;
				text-align: center;
			}
			.rest{
				float: left;
				width: 100%;
			}
			#user_type{
				background-color: white;
				padding: 12px;
			}
			.left {
				float: left;
				width: 50%;
				height: 65%;
				text-align: center;
			}
			.right {
				float: left;
				width: 50%;
				height: 65%;
				text-align: center;
			}
			.form-control-left {
				margin-top: 2.65%;
				width: 60%;
				text-align: center;
				float: right;
				margin-right: 15%;
			}
			.form-control-right {
				width: 60%;
				text-align: center;
				float: left;
				margin-top: 1%;
				margin-left: 15%;
			}
			.btn {
				width: 30%;
				margin-left: 35%;
				margin-right: 35%;
				margin-bottom: 100px;
			}
		</style>
{% endblock css %}

{% block content %}
						<div class="all">
							<div class="banner">
								<form method="POST">
								{% csrf_token %}
								<select name="user_type" id="user_type" style="display: inline-block; float: right;">
									<option value="admin">Admin</option>
									<option value="employee">Employee</option>
									<option value="client">Client</option>
								</select>
								<h1 style="display: inline-block;">Add User</h1>
							</div>
							<div class="left">
								{% for userinput in UserForm %}
									{{ userinput }}
								{% endfor %}
							</div>
							<div class="right">
								<input type="text" name="birth_date" placeholder="birth date" class="form-control form-control-right" onfocus="(this.type=&#x27;date&#x27;)" min="01.01.1900" max="31.12.2020" required id="id_birth_date">
								<input type="text" name="pesel" placeholder="pesel" class="form-control form-control-right" maxlength="11" minlength="11" required id="id_pesel">
								<input type="text" name="id_number" placeholder="id number" class="form-control form-control-right" maxlength="7" minlength="7" required id="id_id_number">
								<input type="text" name="city" placeholder="city" class="form-control form-control-right" required id="id_city">
								<input type="text" name="street" placeholder="street" class="form-control form-control-right" required id="id_street">
								<input type="text" name="street_number" placeholder="street number" class="form-control form-control-right" maxlength="5" required id="id_street_number">
								<input type="text" name="postal_code" placeholder="postal code" class="form-control form-control-right" maxlength="6" minlength="6" required id="id_postal_code">
							</div>
							<button class="btn btn-lg btn-primary btn-block" type="submit" disabled="True" id="subbut">Add</button>
							</form>
						</div>
{% endblock content %}

{% block js %}
	<script type="text/javascript">
		$('#id_password1, #id_password2, #id_postal_code, #id_id_number, #id_pesel').keyup(function(){
			const passCheck = () => {
				const pass1 = document.getElementById('id_password1').value;
				const pass2 = document.getElementById('id_password2').value;
				
				const regex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/gm;

				const regexCheck = regex.test(pass1);
				if(pass1 == pass2 && regexCheck){
					return true;
				}
			}
			const postalCheck = () => {
				const postal = document.getElementById('id_postal_code').value;

				const regex = /[0-9]{2}\-[0-9]{3}/gm;

				if(regex.test(postal)){
					return true
				}
			}
			const id_numberCheck = () => {
				const id_number = document.getElementById('id_id_number').value;

				const regex = /[A-Z]{3}\ [0-9]{3}/gm;

				if(regex.test(id_number)){
					return true
				}
			}
			const peselCheck = () => {
				const pesel = document.getElementById('id_pesel').value;

				const regex = /[0-9]{11}/gm;

				if(regex.test(pesel)){
					return true
				}
			}
			if(passCheck() && postalCheck() && id_numberCheck() && peselCheck()){
				$('#subbut').prop('disabled', false);
			}
		})
	</script>
{% endblock js %}

sets/templates/rents_list_admin.html
{% extends 'rentsBaseAdmin.html' %}

{% block css %}
		<style type="text/css">
			.all {
				width: 100%;
				height: 100%;
				padding-bottom: 100px;
			}
			.banner{
				float: left;
				width: 100%;
				text-align: center;
			}
			.rest{
				float: left;
				width: 100%;
			}
			table{
				border: 1px solid black;
				width: 100%;
				text-align: center;
			}
			th{
				background-color: white;
				border: 1px solid black;
			}
			td{
				border: 1px solid black;
			}
			tr:nth-child(odd) {
				background-color: rgba(255, 255, 255, 0.5);
			}
			.btn{
				background-color: white;
				padding: 15px;
			}
		</style>
{% endblock css %}

{% block content %}
						<div class="all">
							<div class="banner">
								<h1 style="display: inline-block;">Manage rents</h1>
							</div>
							<div class="rest">
								<table id="cars_table">
									<tr>
										<th>Lp.</th>
										<th>USER</th>
										<th>CAR</th>
										<th>START DATE</th>
										<th>END DATE</th>
										<th>INSURANCE</th>
										<th>PRICE</th>
										<th>Delete</th>
									</tr>
									{% for rent in rents %}
									<tr>
										<td>{{ forloop.counter }}</td>
										<td>{{ rent.user }}</td>
										<td>{{ rent.car }}</td>
										<td>{{ rent.rent_starts }}</td>
										<td>{{ rent.rent_ends }}</td>
										<td>{{ rent.additional_insurance }}</td>
										<td>{{ rent.price }} PLN</td>
										<td><a href="/rentdelete/{{ rent.id }}"><svg width='1em' height='1em' viewBox='0 0 16 16' class='bi bi-trash' fill='currentColor'><path d='M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z'/><path fill-rule='evenodd' d='M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z'/></svg></a></td>
									</tr>
									{% endfor %}
								</table>

							</div>
						</div><br><br><br><br><br><br>
{% endblock content %}

sets/templates/user_edit.html
{% extends 'settingsBase.html' %}

{% block css %}
		<style type="text/css">
			.about{
				float: left;
				width: 25%;
			}
			.info{
				float: left;
				width: 75%;
			}
			.about, .info {
				margin-top: 2%;
			}
			p, input{
				height: 40px;
				margin-top: 0;
			}
		</style>
{% endblock css %}

{% block content %}
						<div class="kkk">
							<h1>Edit {{ obj.first_name }} {{ obj.last_name }}</h1>
							<div class="about">
								<p>Birth date:</p>
								<p>PESEL:</p>
								<p>ID NUMBER:</p>
								<p>City:</p>
								<p>Street:</p>
								<p>Street number:</p>
								<p>Postal code:</p>
							</div>
							<div class="info">
								<form method="post" novalidate>
									{% csrf_token %}
									<p>{{ form.birth_date }}</p>
									<p>{{ form.pesel }}</p>
									<p>{{ form.id_number }}</p>
									<p>{{ form.city }}</p>
									<p>{{ form.street }}</p>
									<p>{{ form.street_number }}</p>
									<p>{{ form.postal_code }}</p>
									<button class="btn btn-lg btn-primary btn-block" type="submit" disabled="False" id="subbut">SUBMIT</button>
								</form>
							</div>
						</div>
{% endblock content %}

{% block js %}
	<script type="text/javascript">
		$('#subbut').prop('disabled', false);
		$('#id_postal_code, #id_id_number, #id_pesel').keyup(function(){
			const postalCheck = () => {
				const postal = document.getElementById('id_postal_code').value;

				const regex = /[0-9]{2}\-[0-9]{3}/gm;

				if(regex.test(postal)){
					return true
				}
			}
			const id_numberCheck = () => {
				const id_number = document.getElementById('id_id_number').value;

				const regex = /[A-Z]{3}\ [0-9]{3}/gm;

				if(regex.test(id_number)){
					return true
				}
			}
			const peselCheck = () => {
				const pesel = document.getElementById('id_pesel').value;

				const regex = /[0-9]{11}/gm;

				if(regex.test(pesel)){
					return true
				}
			}
			if(postalCheck() && id_numberCheck() && peselCheck()){
				$('#subbut').prop('disabled', false);
			}
			else{
				$('#subbut').prop('disabled', true);
			}
		})
	</script>
{% endblock js %}