ajax/urls.py
from django.contrib import admin
from django.urls import path
from .views import users, free_days


urlpatterns = [
	path('users/', users, name='ajax-users'),
	path('days/', free_days, name='ajax-days')
]

carrent/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import Home_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', Home_view.as_view(), name='home'),

    path('', include('accounts.urls')),
    path('', include('userprofile.urls')),
    path('', include('sets.urls')),
    path('ajax/', include('ajax.urls')),
    path('', include('rents.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rents/urls.py
from django.urls import path, include
from .views import Rent_view

urlpatterns = [
	path('rent/<int:id>/', Rent_view.as_view(), name='rent')
]

userprofile/urls.py
from django.urls import path, include
from .views import ProfileView, ProfileEdit, PasswordChangeView, RentsView, rent_delete

urlpatterns = [
	path('profile/', ProfileView.as_view(), name='profile'),
	path('profileedit/', ProfileEdit.as_view(), name='profile-edit'),
	path('password/', PasswordChangeView.as_view(), name='password'),
	path('rents/', RentsView.as_view(), name='rents'),
	path('rent_delete/<int:id>', rent_delete, name='rentdelete'),
]

rents/models.py
from django.db import models
from django.contrib.auth.models import User
from cars.models import Car

class Rent(models.Model):
	user 					= models.ForeignKey(User, on_delete=models.CASCADE)
	car 					= models.ForeignKey(Car, on_delete=models.CASCADE)
	rent_starts				= models.DateField()
	rent_ends				= models.DateField()
	additional_insurance	= models.BooleanField(default=False)
	price					= models.IntegerField()

	def first_name(self):
		return self.user.first_name

	def last_name(self):
		return self.user.last_name

	def brand(self):
		return self.car.brand

	def modell(self):
		return self.car.model

userprofile/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput
from django.contrib.auth.models import User
import re
from django.core.exceptions import ValidationError
from .models import Headadmin, Employee, Client


class DateInput(forms.DateInput):
	input_type = 'date'

class MyAuthForm(AuthenticationForm):
	class Meta:
		model = User
		fields = ['username','password']
	def __init__(self, *args, **kwargs):
		super(MyAuthForm, self).__init__(*args, **kwargs)
		self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
		self.fields['username'].label = False
		self.fields['password'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'}) 
		self.fields['password'].label = False

class UserSignupForm(forms.Form):
	username				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'username',
										'class' : 'form-control form-control-left'}))

	password1				= forms.CharField(required = True,
								widget = forms.PasswordInput(
									attrs = {
										'placeholder' : 'password',
										'class' : 'form-control form-control-left'}))

	password2				= forms.CharField(required = True,
								widget = forms.PasswordInput(
									attrs = {
										'placeholder' : 'password',
										'class' : 'form-control form-control-left'}))

	first_name				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'first name',
										'class' : 'form-control form-control-left'}))

	last_name				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'last name',
										'class' : 'form-control form-control-left'}))

	email					= forms.EmailField(required = True,
								widget = forms.EmailInput(
									attrs = {
										'placeholder' : 'email',
										'class' : 'form-control form-control-left'}))
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

	def clean_username(self):
		username = self.cleaned_data['username'].lower()
		r = User.objects.filter(username=username)
		if r.count():
			raise  ValidationError("Username already exists")
		return username

	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		r = User.objects.filter(email=email)
		if r.count():
			raise  ValidationError("Email already exists")
		return email

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')

		if password1 and password2 and password1 != password2:
			raise ValidationError("Password don't match")

		return password2

class ClientSignupForm(forms.ModelForm):
	birth_date				= forms.DateField(required = True,  label="Birth_date",
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'birth date',
										'class' : 'form-control form-control-right',
										'onfocus': "(this.type='date')",
										'min': '01.01.1900',
										'max': '31.12.2020'}))

	pesel					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'pesel',
										'class' : 'form-control form-control-right',
										'maxlength': 11,
										'minlength': 11}))

	id_number				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'id number',
										'class' : 'form-control form-control-right',
										'maxlength': 7,
										'minlength': 7}))

	city					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'city',
										'class' : 'form-control form-control-right'}))

	street					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'street',
										'class' : 'form-control form-control-right'}))

	street_number			= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'street number',
										'class' : 'form-control form-control-right',
										'maxlength': 5}))

	postal_code				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'postal code',
										'class' : 'form-control form-control-right',
										'maxlength': 6,
										'minlength': 6}))

	class Meta:
		model = Client
		fields = ['birth_date', 'pesel', 'id_number', 'city', 'street', 'street_number', 'postal_code']

class EmployeeSignupForm(forms.ModelForm):
	birth_date				= forms.DateField(required = True,  label="Birth_date",
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'birth date',
										'class' : 'form-control form-control-right',
										'onfocus': "(this.type='date')",
										'min': '01.01.1900',
										'max': '31.12.2020'}))

	pesel					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'pesel',
										'class' : 'form-control form-control-right',
										'maxlength': 11,
										'minlength': 11}))

	id_number				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'id number',
										'class' : 'form-control form-control-right',
										'maxlength': 7,
										'minlength': 7}))

	city					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'city',
										'class' : 'form-control form-control-right'}))

	street					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'street',
										'class' : 'form-control form-control-right'}))

	street_number			= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'street number',
										'class' : 'form-control form-control-right',
										'maxlength': 5}))

	postal_code				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'postal code',
										'class' : 'form-control form-control-right',
										'maxlength': 6,
										'minlength': 6}))

	class Meta:
		model = Employee
		fields = ['birth_date', 'pesel', 'id_number', 'city', 'street', 'street_number', 'postal_code']

class HeadadminSignupForm(forms.ModelForm):
	birth_date				= forms.DateField(required = True,  label="Birth_date",
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'birth date',
										'class' : 'form-control form-control-right',
										'onfocus': "(this.type='date')",
										'min': '01.01.1900',
										'max': '31.12.2020'}))

	pesel					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'pesel',
										'class' : 'form-control form-control-right',
										'maxlength': 11,
										'minlength': 11}))

	id_number				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'id number',
										'class' : 'form-control form-control-right',
										'maxlength': 7,
										'minlength': 7}))

	city					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'city',
										'class' : 'form-control form-control-right'}))

	street					= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'street',
										'class' : 'form-control form-control-right'}))

	street_number			= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'street number',
										'class' : 'form-control form-control-right',
										'maxlength': 5}))

	postal_code				= forms.CharField(required = True,
								widget = forms.TextInput(
									attrs = {
										'placeholder' : 'postal code',
										'class' : 'form-control form-control-right',
										'maxlength': 6,
										'minlength': 6}))

	class Meta:
		model = Headadmin
		fields = ['birth_date', 'pesel', 'id_number', 'city', 'street', 'street_number', 'postal_code']

rents/forms.py
from django import forms
from .models import Rent

class RentForm(forms.ModelForm):
	rent_starts 				= forms.DateField(required = True,
									widget = forms.TextInput(
										attrs = {
											'class': 'inp',
											'id': 'datepicker_start',
											'placeholder': 'start',
											'onfocus': "(this.type='date')",
											'min': '01.01.1900',
											'max': '31.12.2020'}))

	rent_ends					= forms.DateField(required = True,
									widget = forms.TextInput(
										attrs = {
											'class': 'inp',
											'id': 'datepicker_end',
											'placeholder': 'ends',
											'onfocus': "(this.type='date')",
											'min': '01.01.1900',
											'max': '31.12.2020'}))

	price						= forms.IntegerField(required = True,
									widget = forms.NumberInput(
										attrs = {
											'hidden': 'true'}))

	additional_insurance		= forms.BooleanField(required = False,
									widget = forms.CheckboxInput(
										attrs = {
											'id': 'insurance'}))

	class Meta:
		model = Rent
		fields = ['rent_starts', 'rent_ends', 'price', 'additional_insurance']

userprofile/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User

class PasswordChangingForm(PasswordChangeForm):
	old_password			= forms.CharField(required=True, widget=forms.PasswordInput(attrs={
								'placeholder': 'Old password',
								'class' : 'form-control form-control-right'}))
	new_password1			= forms.CharField(required=True, widget=forms.PasswordInput(attrs={
								'placeholder': 'Old password',
								'class' : 'form-control form-control-right'}))
	new_password2			= forms.CharField(required=True, widget=forms.PasswordInput(attrs={
								'placeholder': 'Old password',
								'class' : 'form-control form-control-right'}))

	class Meta:
		model = User
		fields = ['old_password', 'new_password1', 'new_password2']

rents/views.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404, HttpResponseRedirect, reverse
from django.views import View
from cars.models import Car
from .forms import RentForm
from .models import Rent

@method_decorator(login_required, name='dispatch')
class Rent_view(View):
	template_name = 'rent.html'

	form = RentForm

	context = {
		'title': 'Rent',
		'form': form,
	}
	def get(self, request, id):
		self.car = get_object_or_404(Car, pk=id)
		self.context['car'] = self.car
		return render(request, self.template_name, self.context)

	def post(self, request, id):
		self.form = RentForm(request.POST)

		if self.form.is_valid():
			rent = self.form.save(commit = False)
			rent.user = request.user
			rent.car = get_object_or_404(Car, pk=id)
			self.form.save()

			return redirect('/')
		return render(request, self.template_name, self.context)

userprofile/views.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views import View
from accounts.models import Client, Employee, Headadmin
from accounts.forms import ClientSignupForm, EmployeeSignupForm, HeadadminSignupForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from .forms import PasswordChangingForm
from rents.models import Rent

@method_decorator(login_required, name='dispatch')
class ProfileView(View):
	template_name = 'profile.html'

	context = {
		'title': 'Profile',
		'active_profile': 'active'
	}

	def get(self, request):
		return render(request, self.template_name, self.context)

@method_decorator(login_required, name='dispatch')
class ProfileEdit(View):
	template_name = 'edit_account.html'

	context = {
		'title': 'Edit profile',
		'active_profile_edit': 'active'
	}

	def get(self, request):
		user = request.user

		try:
			obj = Headadmin.objects.get(user=user.id)
			form = HeadadminSignupForm(request.POST or None, instance=obj)
		except Headadmin.DoesNotExist:
			pass

		try:
			obj = Client.objects.get(user=user.id)
			form = ClientSignupForm(request.POST or None, instance=obj)
		except Client.DoesNotExist:
			pass

		try:
			obj = Employee.objects.get(user=user.id)
			form = EmployeeSignupForm(request.POST or None, instance=obj)
		except Employee.DoesNotExist:
			pass

		self.context['form'] = form

		return render(request, self.template_name, self.context)

	def post(self, request):
		user = request.user
		try:
			obj = Headadmin.objects.get(user=user.id)
			form = HeadadminSignupForm(request.POST or None, instance=obj)
		except Headadmin.DoesNotExist:
			pass

		try:
			obj = Client.objects.get(user=user.id)
			form = ClientSignupForm(request.POST or None, instance=obj)
		except Client.DoesNotExist:
			pass

		try:
			obj = Employee.objects.get(user=user.id)
			form = EmployeeSignupForm(request.POST or None, instance=obj)
		except Employee.DoesNotExist:
			pass

		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('profile'))

@method_decorator(login_required, name='dispatch')
class PasswordChangeView(PasswordChangeView):
	form_class = PasswordChangingForm
	template_name = 'password.html'
	success_url = reverse_lazy('profile')

@method_decorator(login_required, name='dispatch')
class RentsView(View):
	template_name = 'rents.html'
	rents = None

	context = {
		'active_rents': 'active',
		'title': 'Rents',
	}

	def get(self, request):
		user = request.user
		user_id = user.id
		self.rents = Rent.objects.all().filter(user=user_id)
		self.context['rents'] = list(self.rents)

		return render(request, self.template_name, self.context)

@method_decorator(login_required, name='dispatch')
def rent_delete(request, id):
	rent = get_object_or_404(Rent, pk=id)
	rent.delete()
	return HttpResponseRedirect(reverse('rents'))

userprofile/templates/edit_account.html
{% extends 'profileBase.html' %}

{% block css %}
		<style type="text/css">
			.about{
				float: left;
				width: 25%;
			}
			.info{
				float: left;
				width: 75%;
			}
			.about, .info {
				margin-top: 2%;
			}
			p, input{
				height: 40px;
				margin-top: 0;
			}
		</style>
{% endblock css %}

{% block content %}
						<div class="kkk">
							<h1>Edit your account info</h1>
							<div class="about">
								<p>Birth date:</p>
								<p>PESEL:</p>
								<p>ID NUMBER:</p>
								<p>City:</p>
								<p>Street:</p>
								<p>Street number:</p>
								<p>Postal code:</p>
							</div>
							<div class="info">
								<form method="post" novalidate>
									{% csrf_token %}
									<p>{{ form.birth_date }}</p>
									<p>{{ form.pesel }}</p>
									<p>{{ form.id_number }}</p>
									<p>{{ form.city }}</p>
									<p>{{ form.street }}</p>
									<p>{{ form.street_number }}</p>
									<p>{{ form.postal_code }}</p>
									<button class="btn btn-lg btn-primary btn-block" type="submit" disabled="False" id="subbut">SUBMIT</button>
								</form>
							</div>
						</div>
{% endblock content %}

{% block js %}
	<script type="text/javascript">
		$('#subbut').prop('disabled', false);
		$('#id_postal_code, #id_id_number, #id_pesel').keyup(function(){
			const postalCheck = () => {
				const postal = document.getElementById('id_postal_code').value;

				const regex = /[0-9]{2}\-[0-9]{3}/gm;

				if(regex.test(postal)){
					return true
				}
			}
			const id_numberCheck = () => {
				const id_number = document.getElementById('id_id_number').value;

				const regex = /[A-Z]{3}\ [0-9]{3}/gm;

				if(regex.test(id_number)){
					return true
				}
			}
			const peselCheck = () => {
				const pesel = document.getElementById('id_pesel').value;

				const regex = /[0-9]{11}/gm;

				if(regex.test(pesel)){
					return true
				}
			}
			if(postalCheck() && id_numberCheck() && peselCheck()){
				$('#subbut').prop('disabled', false);
			}
			else{
				$('#subbut').prop('disabled', true);
			}
		})
	</script>
{% endblock js %}

userprofile/templates/password.html
{% extends 'profileBase.html' %}

{% block active_password_change %}active{% endblock active_password_change %}

{% block css %}
		<style type="text/css">
			.about{
				float: left;
				width: 25%;
			}
			.info{
				float: left;
				width: 75%;
			}
			.about, .info {
				margin-top: 2%;
			}
			p, input{
				height: 40px;
				margin-top: 0;
			}
		</style>
{% endblock css %}

{% block content %}
						<div class="kkk">
							<h1>Change your password</h1>
							<div class="about">
								<p>Old password:</p>
								<p>New password:</p>
								<p>Confirm new password:</p>
							</div>
							<div class="info">
								<form method="post" novalidate>
									{% csrf_token %}
									<p>{{ form.old_password }}</p>
									<p>{{ form.new_password1 }}</p>
									<p>{{ form.new_password2 }}</p>
									<button class="btn btn-lg btn-primary btn-block" type="submit" disabled="False" id="subbut">SUBMIT</button>
								</form>
							</div>
						</div>
{% endblock content %}

{% block js %}
	<script type="text/javascript">
		$('#id_old_password, #id_new_password1, #id_new_password2').keyup(function(){
			const passCheck = () => {
				const oldpass = document.getElementById('id_old_password').value;
				const pass1 = document.getElementById('id_new_password1').value;
				const pass2 = document.getElementById('id_new_password2').value;
				
				const newRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/gm;
				const oldRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/gm;

				const oldRegexCheck = oldRegex.test(oldpass);

				const regexCheck = newRegex.test(pass1);

				if(pass1 == pass2 && regexCheck && oldRegexCheck){
					return true;
				}
			}
			passCheck();
			if(passCheck()){
				$('#subbut').prop('disabled', false);
			}
		})
	</script>
{% endblock js %}

userprofile/templates/profile.html
{% extends 'profileBase.html' %}

{% block css %}
		<style type="text/css">
			.about{
				float: left;
				width: 25%;
			}
			.info{
				float: left;
				width: 75%;
			}
			.about, .info {
				margin-top: 2%;
			}
		</style>
{% endblock css %}

{% block content %}
						<div class="kkk">
							<h1>Welcome {{ user.first_name }} {{ user.last_name }}</h1>
							<div class="about">
								<p>Username:</p>
								<p>E-mail:</p>
								<p>Role:</p>
								<p>Birth date:</p>
								<p>PESEL:</p>
								<p>ID NUMBER:</p>
								<p>City:</p>
								<p>Street:</p>
								<p>Street number:</p>
								<p>Postal code:</p>
							</div>
							<div class="info">
								<p>{{ user.username }}</p>
								<p>{{ user.email }}</p>
								<p>
									{% if user.is_superuser %}
										Headadmin
									{% elif user.client.is_client %}
										Client
									{% elif user.employee.is_employee %}
										Employee
									{% endif %}
								</p>
								<p>
									{% if user.is_superuser %}
										{{ user.headadmin.birth_date }}
									{% elif user.client.is_client %}
										{{ user.client.birth_date }}
									{% elif user.employee.is_employee %}
										{{ user.employee.birth_date }}
									{% endif %}
								</p>
								<p>
									{% if user.is_superuser %}
										{{ user.headadmin.pesel }}
									{% elif user.client.is_client %}
										{{ user.client.pesel }}
									{% elif user.employee.is_employee %}
										{{ user.employee.pesel }}
									{% endif %}
								</p>
								<p>
									{% if user.is_superuser %}
										{{ user.headadmin.id_number }}
									{% elif user.client.is_client %}
										{{ user.client.id_number }}
									{% elif user.employee.is_employee %}
										{{ user.employee.id_number }}
									{% endif %}
								</p>
								<p>
									{% if user.is_superuser %}
										{{ user.headadmin.city }}
									{% elif user.client.is_client %}
										{{ user.client.city }}
									{% elif user.employee.is_employee %}
										{{ user.employee.city }}
									{% endif %}
								</p>
								<p>
									{% if user.is_superuser %}
										{{ user.headadmin.street }}
									{% elif user.client.is_client %}
										{{ user.client.street }}
									{% elif user.employee.is_employee %}
										{{ user.employee.street }}
									{% endif %}
								</p>
								<p>
									{% if user.is_superuser %}
										{{ user.headadmin.street_number }}
									{% elif user.client.is_client %}
										{{ user.client.street_number }}
									{% elif user.employee.is_employee %}
										{{ user.employee.street_number }}
									{% endif %}
								</p>
								<p>
									{% if user.is_superuser %}
										{{ user.headadmin.postal_code }}
									{% elif user.client.is_client %}
										{{ user.client.postal_code }}
									{% elif user.employee.is_employee %}
										{{ user.employee.postal_code }}
									{% endif %}
								</p>
							</div>
						</div>
{% endblock content %}

userprofile/templates/rents.html
{% extends 'profileBase.html' %}

{% block css %}
		<style type="text/css">
			.all {
				width: 100%;
				height: 100%;
				padding-bottom: 100px;
			}
			.banner{
				float: left;
				width: 100%;
				text-align: center;
			}
			.rest{
				float: left;
				width: 100%;
			}
			table{
				border: 1px solid black;
				width: 100%;
				text-align: center;
			}
			th{
				background-color: white;
				border: 1px solid black;
			}
			td{
				border: 1px solid black;
			}
			tr:nth-child(odd) {
				background-color: rgba(255, 255, 255, 0.5);
			}
			.btn{
				background-color: white;
				padding: 15px;
			}
		</style>
{% endblock css %}

{% block content %}
						<div class="all">
							<div class="banner">
								<h1 style="display: inline-block;">Manage rents</h1>
							</div>
							<div class="rest">
								<table id="cars_table">
									<tr>
										<th>Lp.</th>
										<th>CAR</th>
										<th>START DATE</th>
										<th>END DATE</th>
										<th>INSURANCE</th>
										<th>PRICE</th>
										<th>Delete</th>
									</tr>
									{% for rent in rents %}
									<tr>
										<td>{{ forloop.counter }}</td>
										<td>{{ rent.car }}</td>
										<td>{{ rent.rent_starts }}</td>
										<td>{{ rent.rent_ends }}</td>
										<td>{{ rent.additional_insurance }}</td>
										<td>{{ rent.price }} PLN</td>
										<td><a href="/rent_delete/{{ rent.id }}"><svg width='1em' height='1em' viewBox='0 0 16 16' class='bi bi-trash' fill='currentColor'><path d='M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z'/><path fill-rule='evenodd' d='M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z'/></svg></a></td>
									</tr>
									{% endfor %}
								</table>

							</div>
						</div><br><br><br><br><br><br>
{% endblock content %}